name: Compress Images

on:
  workflow_dispatch:

  push:
    paths:
      - "images/**"

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Optimize images
        uses: calibreapp/image-actions@v1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

          jpgPath: "images"
          pngPath: "images"
          webpPath: "images"

          jpegQuality: "70"
          pngQuality: "70"
          webpQuality: "70"

          maxWidth: 800
          maxHeight: 800

          compressOnly: true
