name: Compress Images

on:
  workflow_dispatch:
  push:
    paths:
      - "images/**"

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Optimize images
        uses: calibreapp/image-actions@v1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # ✅ One input folder for all images
          inputPaths: "images"
          # ✅ Output same folder
          outputPaths: "images"
          compressOnly: true

          # ✅ Compression settings
          jpegQuality: "70"
          pngQuality: "70"
          webpQuality: "70"

          # ✅ Resize large images
          maxWidth: 800
          maxHeight: 800
